remote_theme: just-the-docs/just-the-docs

title: AD Simulation Notes
description: FMTC 자율주행 시뮬레이션 노트

# 검색 활성화
search_enabled: true
search:
  heading_level: 2
  previews: 3

# 색상 테마 (dark / light)
color_scheme: dark

# 네비게이션
nav_sort: case_insensitive

# Footer
gh_edit_link: false

# 기타
aux_links:
  "GitHub":
    - "https://github.com/OIEIyoon/ad-simulation-public"
